services:
  dsdb:
    image: xmpro.azurecr.io/dsdb:${VERSION:-4.4.17-XMR}
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SQLCMDSERVER=db
      - SQLCMDUSER=sa
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-someSaPassword!}
      - SQLCMDDBNAME=master
    
      - DSDB_USERNAME=${DSDB_USERNAME:-someDsDbUser}
      - DSDB_PASSWORD=${DSDB_PASSWORD:-someDsDbPassword!}
  dsdbmigrate:
    image: xmpro.azurecr.io/dsdbmigrate:${VERSION:-4.4.17-XMR}
    depends_on:
      dsdb:
        condition: service_completed_successfully
    environment:
      - DSDB_CONNECTIONSTRING=${DSDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:db;Database=DS;User=someDsDbUser;Password=someDsDbPassword!}
  addbmigrate:
    image: xmpro.azurecr.io/addbmigrate:${VERSION:-4.4.17-XMR}
    depends_on:
      addb:
        condition: service_completed_successfully
    environment:
      - ADDB_CONNECTIONSTRING=${ADDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:db;Database=AD;User=someAdDbUser;Password=someAdDbPassword!}
      - DS_BASEURL_CLIENT=${DS_BASEURL_CLIENT:-https://localhost:5203/}
  ad:
    image: xmpro.azurecr.io/ad:${VERSION:-4.4.17-XMR}
    depends_on:
      addbmigrate:
        condition: service_completed_successfully
      addb:
        condition: service_completed_successfully
    ports:
      - "$AD_PORT:8443"
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - xm__serilog__minimumlevel__default=${AD_LOG_LEVEL:-Information}
      - xm__xmpro__appDesigner__featureFlags__dbMigrationsEnabled=false
      - xm__xmpro__appDesigner__featureFlags__enableHealthChecks=false
      - xm__xmpro__appDesigner__featureFlags__enableLogging=true
      - xm__xmpro__appDesigner__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__xmidentity__server__baseUrl=${SM_BASEURL_SERVER:-https://sm123.devupw2svz.xmpro.com/} ## will be changed once SM container is available
      - xm__xmpro__xmidentity__client__baseUrl=${AD_BASEURL_CLIENT:-https://localhost:5202/}
      - xm__xmpro__xmidentity__client__id=${AD_PRODUCT_ID:-25591cdf-9fb4-48e5-81c8-8816f6d74813} ## currently using SM dev
      #- xm__xmpro__xmidentity__client__id=${AD_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d} ## uncomment this to use SM container, same id as License Function App
      - xm__xmpro__xmidentity__client__sharedkey=${AD_PRODUCT_KEY:-L3rCIy9W5iok+fGqe9HEM5br8qLqoZ0gpqrYf6e9ggM=} ## currently using SM dev
      - xm__xmpro__data__connectionString=${ADDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:db;Database=AD;User=someAdDbUser;Password=someAdDbPassword!}
      - xm__xmpro__xmsettings__data__connectionString=${ADDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:db;Database=AD;User=someAdDbUser;Password=someAdDbPassword!}
      - xm__xmpro__healthChecks__cssPath=ClientApp/src/assets/content/styles/healthui.css
  addb:
    image: xmpro.azurecr.io/addb:${VERSION:-4.4.17-XMR}
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SQLCMDSERVER=db
      - SQLCMDUSER=sa
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-someSaPassword!}
      - SQLCMDDBNAME=master
    
      - ADDB_USERNAME=${ADDB_USERNAME:-someAdDbUser}
      - ADDB_PASSWORD=${ADDB_PASSWORD:-someAdDbPassword!}
  db:
    image: xmpro.azurecr.io/db:${VERSION:-4.4.17-XMR}
    ports:
      - "1433:1433"
    environment:
      - DB_SA_PASSWORD=${DB_SA_PASSWORD:-someSaPassword!}
      - MSSQL_SA_PASSWORD=${DB_SA_PASSWORD:-someSaPassword!}
      # - MSSQL_PID=
      # - MSSQL_TCP_PORT=
  ds:
    image: xmpro.azurecr.io/ds:${VERSION:-4.4.17-XMR}
    depends_on:
      dsdb:
        condition: service_completed_successfully
      dsdbmigrate:
        condition: service_completed_successfully
    ports:
      - "$DS_PORT:8443"
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - xm__serilog__minimumlevel__default=${DS_LOG_LEVEL:-Information}
      - xm__xmpro__data__connectionString=${DSDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:db;Database=DS;User=someDsDbUser;Password=someDsDbPassword!}
      - xm__xmpro__xmsettings__data__connectionString=$DSDB_CONNECTIONSTRING
      - xm__xmpro__dataStreamDesigner__streamHostDownloadBaseUrl=https://download.app.xmpro.com/
      - xm__xmpro__dataStreamDesigner__featureFlags__dbMigrationsEnabled=false
      - xm__xmpro__dataStreamDesigner__featureFlags__enableHealthChecks=false
      - xm__xmpro__dataStreamDesigner__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__healthChecks__cssPath=ClientApp/src/assets/content/styles/healthui.css
      - xm__xmpro__xmidentity__server__baseUrl=${SM_BASEURL_SERVER:-https://sm123.devupw2svz.xmpro.com/} ## will be changed once SM container is available
      - xm__xmpro__xmidentity__client__id=${DS_PRODUCT_ID:-f120eeee-b3c2-477c-9dd8-725879a5bbd7} ## currently using SM dev
      #- xm__xmpro__xmidentity__client__id=${AD_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d} ## uncomment this to use SM container, same id as License Function App
      - xm__xmpro__xmidentity__client__baseUrl=${DS_BASEURL_CLIENT:-https://localhost:5203/}
      - xm__xmpro__xmidentity__client__sharedkey=${DS_PRODUCT_KEY:-0OIQqsAIiSdmzK2CdPWOzc6F5537Vdt6pwTUYzHm3Ik=} ## currently using SM dev
      - xm__xmpro__keyVault__provider=
      - xm__xmpro__keyVault__name=
